### ISSUE TITLE
View controller based status bar on iOS 9 missing

### ISSUE THREAD

**Issue by 1024kilobyte** [dani-gavrilov/GDPerformanceView#1]
First thanks for the project, it's a real help to find ui performance issues. Unfortunately on iOS 9 my status bar is hidden if the PerformanceView is visible. My Code from Application didFinishLaunching:

```
#if DEBUG
    GDPerformanceMonitor.sharedInstance.startMonitoring()
    GDPerformanceMonitor.sharedInstance.appVersionHidden = true
    GDPerformanceMonitor.sharedInstance.deviceVersionHidden = true
#endif
```

I'm using "View controller-based status bar appearance" and my main view implements prefersStatusBarHidden to return false. On iOS 10 the status bar is visible with the PerformanceView on top (z-wise), only on iOS 9 (9.3 to be exact), the PerformanceView is on the same position but the status bar is missing.

**Comment by dani-gavrilov** [comment]
I will check this as soon as possible.

Thank you for using GDPerformanceView.

**Comment by dani-gavrilov** [comment]
Hi there,
Please, update to v1.2.4, it's fixed.
