### ISSUE TITLE
Xcode 8.3 cannot compile due to a mystery  “！”

### ISSUE THREAD

**Issue by ShrinkLynn** [dani-gavrilov/GDPerformanceView#4]
GDPerformanceView ，line 271

**Comment by brduca** [comment]
I'm having the same problem. Apparently removing the unwrap "!" fixes it.

**Comment by dani-gavrilov** [comment]
Please, check out new version [GDPerformanceView-Swift 1.2.0](https://github.com/dani-gavrilov/GDPerformanceView-Swift).
